#!/usr/bin/env python3
"""
generate_bert_params.py
=======================
Reads the .npy weight files produced by export_weights.py and emits two C headers:

  ../bert_params.h  — quantized int8 (elem_t) attention/FFN weights + int32 (acc_t)
                      biases for the Gemmini accelerator; pooler and classifier kept
                      as float32 (they run on the CPU scalar core).

  ../bert_input.h   — a static dummy input sequence (elem_t[SEQ_LEN][HIDDEN_DIM])
                      with small deterministic integer values, matching the style of
                      imagenet/images.h.  Replace with real tokenized embeddings later.

Usage (from repo root or from this directory):
    conda run -n ImageNet python setup_BERT/generate_bert_params.py
    # or simply:
    python3 setup_BERT/generate_bert_params.py

The script must be run AFTER export_weights.py has populated setup_BERT/weights/.

Quantisation note
-----------------
PyTorch linear layers store weight as W[out_features, in_features].
Gemmini's tiled_matmul_auto expects matrix B in layout [K][N] = [in][out].
So every weight matrix is transposed before quantisation.

Symmetric per-tensor int8:
    scale   = max(|W_transposed|) / 127           (floor at 1e-6)
    W_q     = round(W_T / scale).clip(-128,127)   → int8 (elem_t)

Bias (acc_t = int32) lives in accumulator space alongside int8×int8 products.
Assuming the dummy input values are small integers treated at scale 1/127:
    b_q = round(b / (w_scale * input_scale))      where input_scale = 1/127
        = round(b * 127 / w_scale)                → int32 (acc_t)

This is a first-pass quantisation suited for hardware flow testing.
Replace scale factors with proper PTQ/QAT values for accuracy runs.
"""

import os
import sys
import numpy as np

# ── Paths ────────────────────────────────────────────────────────────────────
SCRIPT_DIR   = os.path.dirname(os.path.abspath(__file__))
WEIGHTS_DIR  = os.path.join(SCRIPT_DIR, "weights")
TRANSFORMERS = os.path.join(SCRIPT_DIR, "..")   # ../  (transformers/)
PARAMS_PATH  = os.path.join(TRANSFORMERS, "bert_params.h")
INPUT_PATH   = os.path.join(TRANSFORMERS, "bert_input.h")

# ── Architecture constants (must match bert-tiny-sst2.c) ────────────────────
HIDDEN_DIM    = 128
EXPANSION_DIM = 512
NUM_LAYERS    = 2
NUM_LABELS    = 2
SEQ_LEN       = 128

INPUT_SCALE   = 1.0 / 127.0   # assumed scale for dummy int8 inputs

# ── Helpers ──────────────────────────────────────────────────────────────────

def load(name):
    """Load a weight .npy file by stem (no extension)."""
    path = os.path.join(WEIGHTS_DIR, name + ".npy")
    if not os.path.exists(path):
        sys.exit(f"[ERROR] Weight file not found: {path}\n"
                 "        Run export_weights.py first.")
    return np.load(path).astype(np.float32)


def quantize_weight(W, target_max=127):
    """Symmetric per-tensor int8 quantisation of a 2-D weight array."""
    max_abs  = max(float(np.max(np.abs(W))), 1e-6)
    scale    = max_abs / target_max
    W_q      = np.round(W / scale).clip(-128, 127).astype(np.int8)
    return W_q, scale


def quantize_bias(b, w_scale, in_scale=INPUT_SCALE):
    """
    Scale the bias into accumulator space.
        b_q = round( b / (w_scale * in_scale) )
    """
    denom = w_scale * in_scale
    b_q   = np.round(b / denom).clip(-(2**31), 2**31 - 1).astype(np.int64)
    return b_q


def flat_c(arr):
    """1-D or N-D array → flat C brace-initialiser e.g. {1,-2,3}"""
    return "{" + ",".join(str(int(v)) for v in arr.flatten()) + "}"


def matrix_c(arr):
    """2-D array → nested C brace-initialiser {{row0},{row1},...}"""
    rows = ["{" + ",".join(str(int(v)) for v in row) + "}" for row in arr]
    return "{" + ",".join(rows) + "}"


def float_row(arr):
    return "{" + ",".join(f"{float(v):.8f}f" for v in arr) + "}"


def float_matrix(arr):
    rows = [float_row(row) for row in arr]
    return "{" + ",".join(rows) + "}"


# ── Generate bert_params.h ───────────────────────────────────────────────────

def gen_params():
    L = []

    L += [
        "/* bert_params.h",
        " * Auto-generated by setup_BERT/generate_bert_params.py — DO NOT EDIT.",
        " *",
        " * Quantised weights for BERT-Tiny (M-FAC/bert-tiny-finetuned-sst2).",
        " * elem_t (int8)  : attention and FFN weights, transposed to gemmini layout.",
        " * acc_t  (int32) : biases in accumulator space.",
        " * float          : pooler and classifier (run on CPU).",
        " */",
        "",
        "#ifndef BERT_PARAMS_H",
        "#define BERT_PARAMS_H",
        "",
        "#include <include/gemmini_params.h>",
        "",
    ]

    for layer in range(NUM_LAYERS):
        pfx = f"bert_encoder_layer_{layer}"
        L.append(f"/* ── Encoder layer {layer} {'─'*57}*/")
        L.append("")

        # Attention weight matrices: PyTorch [out=H, in=H] → gemmini [in=H, out=H]
        for tag, npy_stem in [
            ("Wq", f"{pfx}_attention_self_query_weight"),
            ("Wk", f"{pfx}_attention_self_key_weight"),
            ("Wv", f"{pfx}_attention_self_value_weight"),
            ("Wo", f"{pfx}_attention_output_dense_weight"),
        ]:
            W_pt    = load(npy_stem)           # [out=128, in=128]
            W_g     = W_pt.T                   # [in=128, out=128]
            W_q, sc = quantize_weight(W_g)
            # stash scale for bias companion
            globals()[f"_sc_l{layer}_{tag}"] = sc
            L.append(
                f"static const elem_t bert_l{layer}_{tag}"
                f"[{HIDDEN_DIM}][{HIDDEN_DIM}] row_align(1) = {matrix_c(W_q)};"
            )
        L.append("")

        # FFN weight matrices
        # ff1: PyTorch [out=512, in=128] → gemmini [in=128, out=512], flat [128*512]
        ff1_pt      = load(f"{pfx}_intermediate_dense_weight")  # [512,128]
        ff1_g       = ff1_pt.T                                   # [128,512]
        ff1_q, sc1  = quantize_weight(ff1_g)
        globals()[f"_sc_l{layer}_ff1"] = sc1
        L.append(
            f"static const elem_t bert_l{layer}_ff1_w"
            f"[{HIDDEN_DIM * EXPANSION_DIM}] row_align(1) = {flat_c(ff1_q)};"
        )

        # ff2: PyTorch [out=128, in=512] → gemmini [in=512, out=128], flat [512*128]
        ff2_pt      = load(f"{pfx}_output_dense_weight")         # [128,512]
        ff2_g       = ff2_pt.T                                    # [512,128]
        ff2_q, sc2  = quantize_weight(ff2_g)
        globals()[f"_sc_l{layer}_ff2"] = sc2
        L.append(
            f"static const elem_t bert_l{layer}_ff2_w"
            f"[{EXPANSION_DIM * HIDDEN_DIM}] row_align(1) = {flat_c(ff2_q)};"
        )
        L.append("")

        # Biases (acc_t = int32)
        for tag, bias_stem, sc_key in [
            ("Wq_b",  f"{pfx}_attention_self_query_bias",       f"_sc_l{layer}_Wq"),
            ("Wk_b",  f"{pfx}_attention_self_key_bias",         f"_sc_l{layer}_Wk"),
            ("Wv_b",  f"{pfx}_attention_self_value_bias",       f"_sc_l{layer}_Wv"),
            ("Wo_b",  f"{pfx}_attention_output_dense_bias",     f"_sc_l{layer}_Wo"),
        ]:
            b  = load(bias_stem)
            bq = quantize_bias(b, globals()[sc_key])
            L.append(
                f"static const acc_t bert_l{layer}_{tag}"
                f"[{HIDDEN_DIM}] row_align_acc(1) = {flat_c(bq)};"
            )

        b_ff1  = load(f"{pfx}_intermediate_dense_bias")
        bq_ff1 = quantize_bias(b_ff1, globals()[f"_sc_l{layer}_ff1"])
        L.append(
            f"static const acc_t bert_l{layer}_ff1_b"
            f"[{EXPANSION_DIM}] row_align_acc(1) = {flat_c(bq_ff1)};"
        )

        b_ff2  = load(f"{pfx}_output_dense_bias")
        bq_ff2 = quantize_bias(b_ff2, globals()[f"_sc_l{layer}_ff2"])
        L.append(
            f"static const acc_t bert_l{layer}_ff2_b"
            f"[{HIDDEN_DIM}] row_align_acc(1) = {flat_c(bq_ff2)};"
        )
        L.append("")

    # ── Pooler (CPU float, PyTorch layout [out=128, in=128]) ─────────────────
    L += [
        "/* ── Pooler — float32, runs on the CPU scalar core " + "─"*27 + "*/",
        "/*    C code: out[i] = tanh( sum_j( cls_in[j] * bert_pooler_w[i][j] ) + bert_pooler_b[i] ) */",
        "",
    ]
    pw = load("bert_pooler_dense_weight")   # [128, 128], PyTorch [out, in]
    pb = load("bert_pooler_dense_bias")     # [128]
    L.append(
        f"static const float bert_pooler_w[{HIDDEN_DIM}][{HIDDEN_DIM}]"
        f" = {float_matrix(pw)};"
    )
    L.append(
        f"static const float bert_pooler_b[{HIDDEN_DIM}]"
        f" = {float_row(pb)};"
    )
    L.append("")

    # ── Classifier (CPU float, PyTorch layout [out=2, in=128]) ───────────────
    L += [
        "/* ── Classifier — float32, runs on the CPU scalar core " + "─"*24 + "*/",
        "/*    C code: logit[l] = sum_j( cls_pooled[j] * bert_clf_w[l][j] ) + bert_clf_b[l] */",
        "",
    ]
    cw = load("classifier_weight")   # [2, 128]
    cb = load("classifier_bias")     # [2]
    L.append(
        f"static const float bert_clf_w[{NUM_LABELS}][{HIDDEN_DIM}]"
        f" = {float_matrix(cw)};"
    )
    L.append(
        f"static const float bert_clf_b[{NUM_LABELS}]"
        f" = {float_row(cb)};"
    )
    L.append("")
    L.append("#endif /* BERT_PARAMS_H */")
    L.append("")

    with open(PARAMS_PATH, "w") as f:
        f.write("\n".join(L))

    total_weights = NUM_LAYERS * (4 * HIDDEN_DIM * HIDDEN_DIM
                                  + HIDDEN_DIM * EXPANSION_DIM
                                  + EXPANSION_DIM * HIDDEN_DIM)
    print(f"[OK] {PARAMS_PATH}")
    print(f"     {total_weights:,} int8 weight values across {NUM_LAYERS} encoder layers")


# ── Generate bert_input.h ────────────────────────────────────────────────────

def gen_input():
    """
    Emit a dummy embedded input sequence: elem_t bert_input[SEQ_LEN][HIDDEN_DIM].

    Values follow the pattern  ((t*3 + d*7) % 9) - 4  → range [-4, 4].
    This is small enough to avoid int8 overflow and produces a deterministic,
    non-trivial pattern across both the token (t) and embedding (d) dimensions —
    analogous to the real int8 pixel values in imagenet/images.h.

    In full inference:  token_ids → word_embedding + position_embedding
                        + token_type_embedding → LayerNorm → layer_ping.
    """
    arr   = np.zeros((SEQ_LEN, HIDDEN_DIM), dtype=np.int8)
    for t in range(SEQ_LEN):
        for d in range(HIDDEN_DIM):
            arr[t, d] = ((t * 3 + d * 7) % 9) - 4

    rows = ["{" + ",".join(str(int(v)) for v in arr[t]) + "}" for t in range(SEQ_LEN)]

    L = [
        "/* bert_input.h",
        " * Auto-generated by setup_BERT/generate_bert_params.py — DO NOT EDIT.",
        " *",
        " * Dummy tokenised + embedded input for BERT-Tiny hardware testing.",
        " * Values: ((t*3 + d*7) % 9) - 4  →  range [-4, 4] (int8-safe).",
        " * Analogous to imagenet/images.h for the MobileNet benchmark.",
        " *",
        " * Replace with real embedded tokens for an accuracy test:",
        " *   token_ids → word_embed + pos_embed + token_type_embed → LayerNorm",
        " */",
        "",
        "#ifndef BERT_INPUT_H",
        "#define BERT_INPUT_H",
        "",
        "#include <include/gemmini_params.h>",
        "",
        f"static const elem_t bert_input[{SEQ_LEN}][{HIDDEN_DIM}] row_align(1) = {{",
    ]

    # emit each token row on its own line for readability
    for i, row in enumerate(rows):
        comma = "," if i < SEQ_LEN - 1 else ""
        L.append(f"    {row}{comma}")

    L += [
        "};",
        "",
        "#endif /* BERT_INPUT_H */",
        "",
    ]

    with open(INPUT_PATH, "w") as f:
        f.write("\n".join(L))

    print(f"[OK] {INPUT_PATH}")
    print(f"     {SEQ_LEN}×{HIDDEN_DIM} dummy input, values in [-4, 4]")


# ── Generate bert_params_fp.h ─────────────────────────────────────────────────

FP_PARAMS_PATH = os.path.join(TRANSFORMERS, "bert_params_fp.h")


def float_vec(arr):
    """1-D array → C float brace-initialiser with %.7g precision."""
    return "{" + ",".join(f"{float(v):.7g}f" for v in arr.flatten()) + "}"


def float_mat(arr):
    """2-D array → nested C float brace-initialiser."""
    rows = ["{" + ",".join(f"{float(v):.7g}f" for v in row) + "}" for row in arr]
    return "{" + ",".join(rows) + "}"


def gen_params_fp():
    """
    Emit bert_params_fp.h — original float32 weights expressed using elem_t / acc_t
    typedefs from gemmini_params.h.

    Intended for a float-hardware Gemmini configuration where gemmini_params.h
    redefines:
        typedef float   elem_t;
        typedef float   acc_t;

    Weight layout: PyTorch native [out_features, in_features] — NO transpose.
    (bert-tiny-sst2-fp.c accesses W[out_j][in_k], i.e. out = in @ W.T + bias.)

    Array types:
        elem_t  — weight matrices, LN gamma (multiplicative)
        acc_t   — bias vectors, LN beta (additive)
    Both declared with row_align / row_align_acc so the arrays are correctly
    aligned for DMA when used with float Gemmini hardware.

    Intentionally will NOT compile against the standard int8 gemmini_params.h
    (float literals assigned to int8 arrays → compiler error), preventing
    accidental use with the wrong hardware configuration.
    """
    L = []
    L += [
        "/* bert_params_fp.h",
        " * Auto-generated by setup_BERT/generate_bert_params.py — DO NOT EDIT.",
        " *",
        " * Original float32 weights for BERT-Tiny (M-FAC/bert-tiny-finetuned-sst2).",
        " * For use with bert-tiny-sst2-fp.c on FLOAT-hardware Gemmini",
        " * (gemmini_params.h must define  typedef float elem_t / acc_t).",
        " *",
        " * Array types follow gemmini conventions:",
        " *   elem_t (float) : weight matrices, LN gamma — declared with row_align(1)",
        " *   acc_t  (float) : bias vectors, LN beta     — declared with row_align_acc(1)",
        " *",
        " * Weight layout: PyTorch [out_features, in_features] — NO transpose.",
        " * C linear:  out[i][j] = sum_k( in[i][k] * W[j][k] ) + bias[j]",
        " *            i.e. out = in @ W.T + bias  (standard PyTorch linear).",
        " */",
        "",
        "#ifndef BERT_PARAMS_FP_H",
        "#define BERT_PARAMS_FP_H",
        "",
        "#include <include/gemmini_params.h>",
        "",
    ]

    for layer in range(NUM_LAYERS):
        pfx = f"bert_encoder_layer_{layer}"
        L.append(f"/* ── Encoder layer {layer} {'─'*59}*/")
        L.append("")

        # Attention weight matrices: elem_t [out=128][in=128], PyTorch layout
        for tag, npy_stem in [
            ("Wq",  f"{pfx}_attention_self_query_weight"),
            ("Wk",  f"{pfx}_attention_self_key_weight"),
            ("Wv",  f"{pfx}_attention_self_value_weight"),
            ("Wo",  f"{pfx}_attention_output_dense_weight"),
        ]:
            W = load(npy_stem)   # [128, 128]
            L.append(
                f"static const elem_t bert_fp_l{layer}_{tag}"
                f"[{HIDDEN_DIM}][{HIDDEN_DIM}] row_align(1) = {float_mat(W)};"
            )
        L.append("")

        # Attention biases: acc_t [128]
        for tag, stem in [
            ("Wq_b", f"{pfx}_attention_self_query_bias"),
            ("Wk_b", f"{pfx}_attention_self_key_bias"),
            ("Wv_b", f"{pfx}_attention_self_value_bias"),
            ("Wo_b", f"{pfx}_attention_output_dense_bias"),
        ]:
            b = load(stem)
            L.append(
                f"static const acc_t bert_fp_l{layer}_{tag}"
                f"[{HIDDEN_DIM}] row_align_acc(1) = {float_vec(b)};"
            )
        L.append("")

        # Attention output LayerNorm: gamma=elem_t (scale), beta=acc_t (offset)
        attn_ln_g = load(f"{pfx}_attention_output_LayerNorm_weight")
        attn_ln_b = load(f"{pfx}_attention_output_LayerNorm_bias")
        L.append(f"static const elem_t bert_fp_l{layer}_attn_ln_gamma[{HIDDEN_DIM}] row_align(1)     = {float_vec(attn_ln_g)};")
        L.append(f"static const acc_t  bert_fp_l{layer}_attn_ln_beta [{HIDDEN_DIM}] row_align_acc(1) = {float_vec(attn_ln_b)};")
        L.append("")

        # FF1: elem_t weight [out=512][in=128], acc_t bias [512]
        ff1 = load(f"{pfx}_intermediate_dense_weight")
        L.append(
            f"static const elem_t bert_fp_l{layer}_ff1_w"
            f"[{EXPANSION_DIM}][{HIDDEN_DIM}] row_align(1) = {float_mat(ff1)};"
        )
        ff1_b = load(f"{pfx}_intermediate_dense_bias")
        L.append(
            f"static const acc_t bert_fp_l{layer}_ff1_b"
            f"[{EXPANSION_DIM}] row_align_acc(1) = {float_vec(ff1_b)};"
        )
        L.append("")

        # FF2: elem_t weight [out=128][in=512], acc_t bias [128]
        ff2 = load(f"{pfx}_output_dense_weight")
        L.append(
            f"static const elem_t bert_fp_l{layer}_ff2_w"
            f"[{HIDDEN_DIM}][{EXPANSION_DIM}] row_align(1) = {float_mat(ff2)};"
        )
        ff2_b = load(f"{pfx}_output_dense_bias")
        L.append(
            f"static const acc_t bert_fp_l{layer}_ff2_b"
            f"[{HIDDEN_DIM}] row_align_acc(1) = {float_vec(ff2_b)};"
        )
        L.append("")

        # FFN output LayerNorm: gamma=elem_t, beta=acc_t
        ffn_ln_g = load(f"{pfx}_output_LayerNorm_weight")
        ffn_ln_b = load(f"{pfx}_output_LayerNorm_bias")
        L.append(f"static const elem_t bert_fp_l{layer}_ffn_ln_gamma[{HIDDEN_DIM}] row_align(1)     = {float_vec(ffn_ln_g)};")
        L.append(f"static const acc_t  bert_fp_l{layer}_ffn_ln_beta [{HIDDEN_DIM}] row_align_acc(1) = {float_vec(ffn_ln_b)};")
        L.append("")

    # ── Pooler ────────────────────────────────────────────────────────────────
    L += [
        "/* ── Pooler {'─'*61}*/",
        "/*    elem_t weight [out=128][in=128], acc_t bias [128]            */",
        "",
    ]
    L.append(
        f"static const elem_t bert_fp_pooler_w[{HIDDEN_DIM}][{HIDDEN_DIM}] row_align(1) = "
        f"{float_mat(load('bert_pooler_dense_weight'))};"
    )
    L.append(
        f"static const acc_t bert_fp_pooler_b[{HIDDEN_DIM}] row_align_acc(1) = "
        f"{float_vec(load('bert_pooler_dense_bias'))};"
    )
    L.append("")

    # ── Classifier ────────────────────────────────────────────────────────────
    L += [
        "/* ── Classifier {'─'*57}*/",
        "/*    elem_t weight [out=2][in=128], acc_t bias [2]                */",
        "",
    ]
    L.append(
        f"static const elem_t bert_fp_clf_w[{NUM_LABELS}][{HIDDEN_DIM}] row_align(1) = "
        f"{float_mat(load('classifier_weight'))};"
    )
    L.append(
        f"static const acc_t bert_fp_clf_b[{NUM_LABELS}] row_align_acc(1) = "
        f"{float_vec(load('classifier_bias'))};"
    )
    L.append("")
    L.append("#endif /* BERT_PARAMS_FP_H */")
    L.append("")

    with open(FP_PARAMS_PATH, "w") as f:
        f.write("\n".join(L))

    total_elem = NUM_LAYERS * (4 * HIDDEN_DIM * HIDDEN_DIM
                               + EXPANSION_DIM * HIDDEN_DIM
                               + HIDDEN_DIM * EXPANSION_DIM)
    print(f"[OK] {FP_PARAMS_PATH}")
    print(f"     {total_elem:,} elem_t values (float32 originals) — for float Gemmini hardware")


# ── Main ─────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("Generating BERT-Tiny C headers from .npy weights...\n")
    gen_params()
    gen_params_fp()
    gen_input()
    print("\nDone.  Headers generated:")
    print(f"  {PARAMS_PATH}")
    print(f"  {FP_PARAMS_PATH}")
    print(f"  {INPUT_PATH}")
    print("\nBuild — Gemmini int8 path:")
    print("  riscv64-unknown-elf-gcc -O2 -DBAREMETAL -Iinclude \\")
    print("      transformers/bert-tiny-sst2.c -o bert-tiny-sst2-baremetal -lm")
    print("\nBuild — CPU float32 reference path:")
    print("  riscv64-unknown-elf-gcc -O2 -DBAREMETAL -Iinclude \\")
    print("      transformers/bert-tiny-sst2-fp.c -o bert-tiny-sst2-fp-baremetal -lm")
